### ISSUE TITLE
How can I train with my own data to achieve 3D reconstruction？

### ISSUE THREAD

**Issue by BCL123456-BAL** [SeanGuo063/NDVG#1]
What a wonderful job you've done! Your model is not only amazing, but also very fast. I really admire your talent and efforts.

I am also interested in this direction and would like to try out your model. I wonder if it is convenient for you to publish the training method of the model, so that it can use the data I provide for 3D reconstruction?

**Comment by SeanGuo063** [comment]
Thanks. To train the model, you can refer to the instruction of training script in README.md. To use your own data, you can either organize the structure of your data according to HyperNeRF dataset, or write a new dataloader for your data structure.
