### ISSUE TITLE
What do transforms_val.json and val files do, and how do I get them

### ISSUE THREAD

**Issue by BCL123456-BAL** [SeanGuo063/NDVG#2]

**Comment by SeanGuo063** [comment]
There are three types of data for each scene in dnerf dataset: train, validation and test. transforms_val.json contains images, pose and camera informations for validation data. Validation data could be used to choose your best model during training. They are contained in the dnerf dataset, you can download them use https://www.dropbox.com/s/0bf6fl0ye2vz3vr/data.zip?dl=0

**Comment by BCL123456-BAL** [comment]
Thank you very much for your reply. 
I want to migrate your work to video data captured in the real world, extracting video frames with Ffmpeg and extracting camera parameters with Colmap. 
But I learned that the data set used by D-Nerf was synthesized using blender. Whether its verification set must be a set of pictures of the continuous action of the object in one visual direction.

**Comment by SeanGuo063** [comment]
Verification set could be different visual directions with training set, so that you can check whether your model could render good quality images of views which are different from training views.
